# Generated by Django 4.2.11 on 2026-07-07 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the department', primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Unique department code (e.g., ENG for Engineering)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Department name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the department', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the department is active (soft delete)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Auto-set on creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Auto-updated on save')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='departments_code_9f933a_idx'), models.Index(fields=['is_active'], name='departments_is_acti_a777bd_idx')],
            },
        ),
    ]
