# Generated by Django 4.2.11 on 2026-07-07 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequestModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the leave request', primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('UNPAID', 'Unpaid Leave'), ('MATERNITY', 'Maternity Leave')], help_text='Type of leave: ANNUAL, SICK, UNPAID, or MATERNITY', max_length=20)),
                ('start_date', models.DateField(db_index=True, help_text='Start date of the leave')),
                ('end_date', models.DateField(db_index=True, help_text='End date of the leave')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Status: PENDING, APPROVED, or REJECTED', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the leave', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Date and time the request was reviewed (set on approve/reject)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Auto-set on creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Auto-updated on save')),
                ('employee', models.ForeignKey(help_text='Reference to Employee', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employeemodel')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Employee who reviewed this request (set on approve/reject)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to='employees.employeemodel')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'db_table': 'leave_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='leave_reque_employe_fd03a1_idx'), models.Index(fields=['status'], name='leave_reque_status_401183_idx'), models.Index(fields=['start_date', 'end_date'], name='leave_reque_start_d_08703b_idx')],
            },
        ),
    ]
