# Generated by Django 4.2.11 on 2026-07-07 12:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('employee_number', models.CharField(db_index=True, help_text='Unique employee identifier (e.g., EMP-001)', max_length=20, unique=True)),
                ('first_name', models.CharField(help_text="Employee's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Employee's last name", max_length=100)),
                ('email', models.EmailField(db_index=True, help_text='Unique email address', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('job_title', models.CharField(help_text="Employee's job title", max_length=100)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract')], default='FULL_TIME', help_text='Employment type: FULL_TIME, PART_TIME, or CONTRACT', max_length=20)),
                ('hire_date', models.DateField(help_text='Date the employee was hired')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the employee', primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the employee is active (soft delete)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Auto-set on creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Auto-updated on save')),
                ('department', models.ForeignKey(help_text='Reference to Department', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='departments.departmentmodel')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['employee_number'],
                'indexes': [models.Index(fields=['employee_number'], name='employees_employe_68f2c7_idx'), models.Index(fields=['email'], name='employees_email_f66e96_idx'), models.Index(fields=['is_active'], name='employees_is_acti_e91717_idx'), models.Index(fields=['first_name', 'last_name'], name='employees_first_n_235346_idx')],
            },
        ),
    ]
